modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="chroma"
version="1.0.0"
displayName="Chroma"
description='''
Chroma adds infinite (16,777,216) RGB color dyeing to Minecraft's dyeable blocks and items via a custom Dyeing Table.
Gradient mode lets you apply smooth color transitions across an entire stack.
Built in optional compatibility with 11 mods: Blahaj, Handcrafted, Another Furniture,
MrCrayfish Refurbished, Create, Sophisticated Backpacks, Sophisticated Storage,
Supplementaries, Macaw's Furniture, Quark, and Applied Energistics 2.
    '''

[[dependencies.chroma]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="blahaj"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="handcrafted"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="another_furniture"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="cfm"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="create"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="sophisticatedbackpacks"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="sophisticatedstorage"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="supplementaries"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="mcwfurnitures"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="quark"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.chroma]]
modId="ae2"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"